export const ellaQuestion = {
    "Activity": [
        'How do I access the Activity Sync Module? ',
        'How do I Sync my Activity in TraCE CRM?',
        'What are the different types of interactions?',
        'How do I add documents to an account or opportunity?',
        'Can I create an opportunity today and tag meetings and tasks I did last week?',
        'Can I Track records from Outlook in TraCE using the “Set Regarding” for Opportunities and Accounts?',
        'Can I forward/write new emails to/from TraCE?',
        'How do I create an activity?',
        'Why do I create an activity?',
        'What is the difference between Activity & Conversation?',
        'What are digital methods to capture an activity?'
    ],
    'Lead': [
        'When do I create a “New Lead”?',
        'What’s the difference between a LEAD and an (unqualified) Opportunity?',
        'How to archive a lead?',
        'How to restore a lead?',
        'How to qualify a lead?',
        'How to create opportunity from a lead?',
        'How to nurture a lead?',
        'How to edit a lead?',
        'How to check the history of a lead/the changes that a lead has undergone since its creation?',
        'How do I close a lead?',
        'Why should I even nurture a lead and how is it done?',
        'How to nurture a lead?'
    ],
    'Contacts': [
        'How to create a contact in TraCE?',
        'How to edit a contact?',
        'How does local contact search work?',
        'How can I see if a contact is tagged to any activity/lead/campaign/opportunity?',
        'How do I filter out my Private Contacts in Outlook from getting synchronized in TraCE?',
        'What are the various methods to capture a contact into the system?',
        'Why should I enrich a contact when it is already captured and saved in the system?',
        'How do I delete a contact?'
    ],
    'Account': [
        'How do I gain access to a given account?',
        'How do I find out if an account is present in the system and who owns it?',
        'How do I create a Global Account Structure in TraCE?',
        'In what way can I tag the buyer organizations and contacts to opportunities?',
        'How do I convert my lead to a “prospect” Account?',
        'How do I create a new account?',
        'What are the different ways of creating an account?',
        'What is an Assignment Reference?',
        'What is the need to create an Assignment Reference for an existing account?',
        'Why can’t I create an opportunity in my ROM account?',
        'How can I share my account in TraCE?',
        'How do I view Accounts/Opportunities/Leads/Contacts in TraCE?',
        'Who has to approve to allow a ROM account for creating opportunities?',
        'Can I engage with a non-Wipro account?',
        'How has my account lifecycle stage changed automatically?',
        'How has the system updated the customer contact details on my account?',
        'How can I request assignment reference on an account?',
        'Why did the account classification change to reserve for my account?'
    ],
    'Opportunity': [
        'How do I create a new opportunity?',
        'When will my name appear in the dropdown list of the Vertical Sales Owner?',
        'What should I do in case a disabled user owns an opportunity?',
        'How do I get access to an Opportunity?',
        'What is the procedure to close an Opportunity manually?',
        'What are the prerequisites to create an Opportunity in TraCE?',
        'What are the steps to modify the opportunity engagement start and end date?',
        'How do I add multiple service lines for an opportunity?',
        'How do I change the status of an opportunity to inactive?',
        'How do I change the estimated revenue of an opportunity?',
        'What is the procedure to change the Estimated Closure date for an opportunity?',
        'How do I enter the actual revenue for an opportunity?',
        'How do I update dual credit?',
        'When will I be able to move from one stage to another in the Opportunity Life Cycle?',
        'How do I update the opportunity name?',
        'How do I add a competitor?',
        'How do I hard close an Opportunity?',
        'How do I change the opportunity source from RFI/Empanelment to RFP/RFR?',
        'How do I add a new service line to an existing opportunity?',
        'When do I mark an opportunity as ‘At Risk’?',
        'How do I ensure that an opportunity record appears in the Order Booking forecast list?',
        'When does a Residual Opportunity come into picture?',
        'Can I re-open a closed opportunity?',
        'Can I book an order before the opportunity is hard closed?',
        'Can I change information entered in different data fields?',
        'Can I end the sales cycle at any time and in any stage?',
        'Can I edit a closed opportunity?',
        'What are the different revenue projection options?',
        'What is a Strategic Deal?',
        'What is Deal Coaching and how long does the process generally go on?',
        'How can a Deal Coach help to nurture an opportunity?',
        'What is a Customer Success story and when is it required?',
        'What is a renewal or incremental opportunity?',
        'What are the different types of reports that can be generated?',
        'While tagging SAP code to an opportunity, SAP code look-up shows no values?',
        'How do I create indents with the shared CRM reference number when I get an error that ‘CRM table does not exist’ as the project creation flag is marked as ‘N’?',
        'How do I Tag a specific person as DM if the name does not appear in the DM look up?',
        'Why certain opportunities are tagged to my name without being initiated by me?'
    ],
    'Order': [
        'What is Order Booking and how do I create Order Booking?',
        'What is an Amendment?',
        'How do I amend an existing order?',
        'Who should approve an order? Is it the Vertical/SL sales Head?',
        'What is an Order at Risk (OR) How do I create an Order at Risk?',
        'Which BFM would receive the order approval requests – Geo or Vertical?',
        'Is email based approval allowed in the system?',
        'Can an email approval from customer be treated in lieu of “SOW/PO” for amendments?',
        'The BFM may delay approving the order due to his workload, how does TraCE system help in resolving this issue?',
        'Is a SOW or PO doc required for each small amendment or new order renewal?',
        ''
    ],
    'GenericFeatures': [
        'How to export from table/listing page?',
        'How to customize table/listing page view?',
        'How does global search work?',
        'While logged onto TraCE, how will I know if my request gets approved or rejected?',
        'What are the salient features of the Home page'
    ]
}