// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from "./.env";

export const environment = {
  production: false,
  //IsConsoleLog : false,
  // daUrl: "http://localhost:4321/",
  // daApiBaseUrl : 'https://quapi-dev.wipro.com/L2O.DA.Api/api/',
  version: env.npm_package_version + "-dev",
  // serverUrl: 'http://10.143.98.152:3000',
  // serverUrl: "http://localhost:3000",
  // l2oBaseUrlOpportunityDecript:
  //   "https://quapi-dev.wipro.com/L2O.Sprint4.Api/api/",
  // l2oBaseUrlOpportunity:
  //   "https://quapi-dev.wipro.com/L2O.Sprint4.Api_Encrypt/api/",
  // toolkitUrl: "https://rsappsdev.wipro.com/",
  // syncredirect: "http://localhost:4200",
  //outlook url
  // outLookUrl: "https://outlook.office365.com",
  // accountPlanUrl: 'https://accountplanuat.wipro.com',
  // l2oBaseUrlOrder: "https://quapi-dev.wipro.com/L2O.Sprint7.Api/api/",
  // l2oBaseUrl: "https://quapi-dev.wipro.com/L2O.Sprint1_2.Api/api/",
  // l3oBaseUrl: "https://quapi-dev.wipro.com/L2O.Sprint3.Api/api/",
  // l2oFileUploadBaseUrl:
  //   "https://quapi-dev.wipro.com/L2O.Sprint1_2.Api/api/Storage/UploadDocument",
  // CommonBaseUrl: "https://quapi-dev.wipro.com/L2O.Common.Services.Api/api/",
  // // camunda_BASE_URL: 'https://10.208.116.172:', //'http://10.200.35.38:4500/',
  // camunda_BASE_URL: "https://camundaqa.wipro.com:", //"https://wiis-orion-07.wipro.com:",
 // envName: "DEV",
  //encryptFlag : true,
  // camundaPorts: {
  //   create: "8058",
  //   modif: "8059",
  //   assign: "6060",
  //   reserve: "7070",
  //   reminder: '8057', // '4505',
  //   salesOrder: '8054',// '4503',
  //   IFandCO: '8055', //'4517',
  //   orderModification: '8056', //'4520'
  // },
  // encDecConfig: {
  //   key: "DecryptionDecrip"
  // },
  userHash: false,
  // outlookConfig: {
  //   instance: "https://login.microsoftonline.com/",
  //   tenant: "258ac4e4-146a-411e-9dc8-79a9e12fd6da",
  //   clientId: "d37e5901-9e1f-4142-85e6-09abc618dae6",
  //   redirectUri: "http://localhost:4200",
  //   response_mode: "id_token+token",
  //   postLogoutRedirectUri: "http://localhost:4200",
  //   endpoints: {
  //     "https://outlook.office365.com": "https://outlook.office365.com",
  //     "https://analysis.windows.net/powerbi/api":
  //       "https://analysis.windows.net/powerbi/api"
  //   },
  //   navigateToLoginRequestUrl: false
  // },
  // authConfig: {
  //   domainUrl: "https://wipfsuat01.wipro.com/adfs",
  //   loginUrl: "https://wipfsuat01.wipro.com/adfs/oauth2/authorize",
  //   logoutUrl: "https://wipfsuat01.wipro.com/adfs/oauth2/logout",
  //   redirectUrl: "http://localhost:4200/auth/redirect", //'https://l2o-app.azurewebsites.net'
  //   //clientId: 'ef6d9135-e4d0-4e4b-acbb-fd81e5e45cf9',
  //   scope: "",
  //   resource: "https://quantumt.wipro.com/api/data/v9.0/",
  //   responseType: "code",
  //   tokenEndpoint: "https://wipfsuat01.wipro.com/adfs/oauth2/token",
  //   requestAccessToken: true,
  //   grantType: "authorization_code",
  //   clientSecret: "3qFLLagz88665aM0iw6yWZUOjSywikHTWJKzoqke",
  //   clientId: "05b31483-b5e6-40a8-98af-9ffff799ede7", //'21fad7f8-20fd-48fb-8f88-7bb306a9f8f4',
  //   key: "Gjpn9-Jc9ZCOzskrw0tEu5Bj35T5kiU_KtyjpwZy", //'3qFLLagz88665aM0iw6yWZUOjSywikHTWJKzoqke',
  //   url: "https://quantumt.wipro.com/"
  // },
  // Sprint 5 dev Base URL starts here
  // sprint5BaseUrl: {
  //   // QaURL2: 'https://quapi-dev.wipro.com/L2O.Sprint1_2.Api/',
  //   QaURL5A: "https://quapi-dev.wipro.com/L2O.Sprint5A.Api/",
  //   QaURL: "https://quantumdps-qa.wipro.com/DEV.ALLIED.DPS/",
  //   QaURL4: "https://quapi-dev.wipro.com/L2O.Sprint4.Api/",
  //   genaralFileUpLoad:
  //     "https://quapi-dev.wipro.com/L2O.Common.Services.Api/api/v1/StorageCommon/UploadDocument_V_1",
  //   uploaddoc:
  //     "https://quapi-dev.wipro.com/L2O.Sprint1_2.Api/api/Storage/UploadDocument"
  // },
  // Sprint 5 dev Base URL ends here
  // wittyParrotIframe: "https://mock-tokenhandler.azurewebsites.net/index.html",
  // daCommunicationUrl: "http://localhost:4321",
  // wittyParrotIframe:'http://localhost:4320/DA/OPPORTUNITY/DEALS/'
  //enableCipher: true
};

/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
