export class CommitmentRegister
{
    Name:string;
    Number:string;
    RANumber:string;
    Parentaccount:string;
    Owner:string;
    City:string;
    Country;
    Classification:string;
    Type:string;
    Primary:string;
    Sbu:string;
    Vertical:string;
    Subvertical:string;
    CountryReference:string;
    RegionReference:string;
    GeoReference:string;
    isCheccked:boolean;
}